CREATE DATABASE Quan_li_sinh_vien
GO
USE Quan_li_sinh_vien
GO

CREATE TABLE Khoa
(
MaKhoa VARCHAR(10) PRIMARY KEY,
TenKhoa NVARCHAR(100) NOT NULL,
NamThanhLap INT
)
GO

CREATE TABLE KhoaHoc
(
MaKhoaHoc VARCHAR(10) PRIMARY KEY,
NamBatDau INT,
NamKetThuc int
)
GO

CREATE TABLE ChuongTrinhHoc
(
MaCT VARCHAR(10) PRIMARY key,
TenCT NVARCHAR(100)
)
GO

CREATE TABLE Lop
(
MaLop VARCHAR(10) PRIMARY KEY,
MaKhoa VARCHAR(10) NOT NULL,
MaKhoaHoc VARCHAR(10) NOT NULL,
MaCT VARCHAR(10) NOT NULL,
STT INT

FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa),
FOREIGN KEY (MaKhoaHoc) REFERENCES KhoaHoc(MaKhoaHoc),
FOREIGN KEY (MaCT) REFERENCES ChuongTrinhHoc(MaCT)
)
GO
CREATE TABLE SinhVien
(
MaSV VARCHAR(10) PRIMARY KEY,
HoTen VARCHAR(100),
NamSinh INT,
DanToc NVARCHAR(20),
MaLop VARCHAR(10) NOT null

FOREIGN KEY (MaLop) REFERENCES Lop(MaLop)
)
GO

CREATE TABLE MonHoc
(
MaMonHoc VARCHAR(10) PRIMARY KEY,
MaKhoa VARCHAR(10) NOT null,
TenMH NVARCHAR(100)

FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)
)
GO

CREATE TABLE KetQua
(
MaSV VARCHAR(10) NOT null,
MaMonHoc VARCHAR(10) NOT NULL,
LanThi INT NOT null,
DiemThi float

PRIMARY KEY (MaSV , MaMonHoc, LanThi),
FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV),
FOREIGN KEY (MaMonHoc) REFERENCES MonHoc(MaMonHoc)
)
GO


CREATE TABLE GiangKhoa
(
MaCT VARCHAR(10) NOT null,
MaKhoa VARCHAR(10) NOT NULL,
MaMonHoc VARCHAR(10) NOT NULL,
NamHoc INT NOT null,
HocKi INT,
STLT INT,
STTH INT,
SoTinChi int

PRIMARY KEY (MaCT, MaKhoa, MaMonHoc, NamHoc),

FOREIGN KEY (MaCT) REFERENCES ChuongTrinhHoc(MaCT),
FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa),
FOREIGN KEY (MaMonHoc) REFERENCES MonHoc(MaMonHoc)

)
GO